p403n1x/randomlife

app/controllers/options_controller.rb
methodes options_controller faites
=> options controller done

app/controllers/application_controller.rb, app/controllers/categories_controller.rb, app/controllers/options_controller.rb, app/controllers/pages_controller.rb, app/models/category.rb, app/views/categories/index.html.erb, db/migrate/20200225155101_rename_type_in_categories.rb, db/schema.rb, db/seeds.rb
coucou olivier
did controller categories
modified category model to replace 'type' with 'kind'
created view for categories index
=> categories controller view and model modif

app/controllers/pages_controller.rb, app/controllers/tasks_controller.rb, app/views/tasks/edit.html.erb, config/routes.rb
Controller Task avec les méthodes : ok
=> controller tasks done

app/assets/stylesheets/components/_navbar.scss, app/controllers/categories_controller.rb, app/controllers/pages_controller.rb, app/controllers/users_controller.rb, app/views/layouts/application.html.erb, app/views/shared/_navbar.html.erb, app/views/users/show.html.erb
coucou olivier
created navbar!
=> navbar done

app/javascript/components/navbar.js, app/javascript/packs/application.js, app/views/shared/_navbar.html.erb, package.json, yarn.lock
coucou olivier 
added typed js to navbar
=> navbar with typed js

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_userprofil.scss, app/controllers/options_controller.rb, app/views/layouts/application.html.erb, app/views/options/index.html.erb, app/views/shared/_card_category.html.erb, app/views/shared/_flashes.html.erb, app/views/shared/_userprofil.html.erb
=> Components

app/controllers/tasks_controller.rb, app/views/tasks/new.html.erb, app/views/tasks/show.html.erb, db/migrate/20200227131759_change_start_date_to_be_date_in_tasks.rb, db/schema.rb
Edit et create de task done
Il restera la mise en forme
=> new et create task done, reste mise en forme

app/assets/stylesheets/components/_cards.scss, app/controllers/users_controller.rb, app/views/layouts/application.html.erb, app/views/shared/_navbar.html.erb, app/views/users/edit.html.erb, app/views/users/show.html.erb, config/routes.rb
=> Profiluser

app/assets/stylesheets/components/_button.scss, app/controllers/categories_controller.rb, app/models/category.rb, app/models/group.rb, app/views/categories/index.html.erb, app/views/categories/new.html.erb
Coucou!
Dashboard showing photos, and add category button.
User can now add a category.
=> Dashboard display with pics and add category

app/controllers/assigned_tasks_controller.rb, app/views/assigned_tasks/edit.html.erb, app/views/assigned_tasks/index.html.erb, app/views/shared/_navbar.html.erb, config/routes.rb
=> listing des assigned task et lien dans navbar

app/views/categories/index.html.erb
Coucou 
Petit changement de format dans Dashboard
=> small format change to Dashboard

app/controllers/assigned_tasks_controller.rb, app/controllers/tasks_controller.rb, app/models/category.rb, app/models/task.rb, app/views/assigned_tasks/edit.html.erb, app/views/assigned_tasks/index.html.erb, app/views/tasks/show.html.erb
première version des assigned task
=> list assigned task et done ok

app/views/assigned_tasks/index.html.erb, app/views/assigned_tasks/update.html.erb, config/initializers/rails_defaults.rb
List des assigned task et done : OK
=> mise en page assigned tasks

app/assets/stylesheets/application.scss, app/assets/stylesheets/config/_colors.scss, app/assets/stylesheets/config/_fonts.scss, app/javascript/packs/application.js, app/javascript/plugins/flatpickr.js, app/views/tasks/new.html.erb, package.json, yarn.lock
Petit calendrier des familles et gif
=> calendar sur page task + gif

.gitignore, Gemfile, Gemfile.lock, app/controllers/categories_controller.rb, app/models/category.rb, app/views/categories/index.html.erb, config/environments/development.rb, config/storage.yml, db/migrate/20200228123027_create_active_storage_tables.active_storage.rb, db/schema.rb, db/seeds.rb
coucou !
Maintentant, l'utilisateur peut créer une nouvelle catégorie et attacher une photo qui correspond, et la photo sera stockée dans Cloudinary.
Et bim!
=> Cloudinary

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_avatar.scss, app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_cards.scss, app/assets/stylesheets/config/_bootstrap_variables.scss, app/assets/stylesheets/config/_colors.scss, app/controllers/pages_controller.rb, app/views/categories/index.html.erb, app/views/pages/home.html.erb, app/views/users/show.html.erb
=> Frontmodifs

app/assets/stylesheets/components/_cards.scss, app/views/categories/index.html.erb, app/views/users/show.html.erb
=> quelques modifs

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_list.scss, app/controllers/options_controller.rb, app/views/option_categories/index.html.erb, app/views/options/destroy.html.erb, app/views/options/index.html.erb, app/views/options/show.html.erb
index, create et delete options
=> index, create et delete options

app/controllers/actions_controller.rb, app/views/actions/show.html.erb, app/views/options/index.html.erb
Roulette fonctionnelle mais encore du front a faire et tres peu de back (affichage ou non des options en selected true)
=> roulette fonctionnelle

app/controllers/groups_controller.rb, app/controllers/users/registrations_controller.rb, app/controllers/users_controller.rb, app/models/user.rb, app/views/groups/show.html.erb, config/routes.rb
Coucou,
As a user, I can now add one or more users to a group.
Next step is to send email to these new users so they can sign up.
=> add users to group

app/controllers/users_controller.rb, app/models/user.rb, app/views/users/show.html.erb
Edit Profile --> user can now upload a photo to his profile page!
=> user can add photo to profile

app/controllers/actions_controller.rb, app/views/actions/index.html.erb, app/views/assigned_tasks/index.html.erb, config/routes.rb
modifs sur les group activities
=> modifs group activities

app/views/actions/index.html.erb, app/views/shared/_roulette.html.erb
Roulette wheel now includes the profile pictures
=> Roulette wheel with photos

app/views/actions/index.html.erb, app/views/categories/index.html.erb, app/views/option_categories/index.html.erb, app/views/users/show.html.erb
My Group Activities - avatar photos now displaying
Changed button labels to something less clinical on Dashboard
Edit profile - added upload photo buttons
=> avatar photos on group activities page plus button improvements

app/views/actions/index.html.erb, app/views/categories/index.html.erb, app/views/option_categories/index.html.erb, app/views/options/index.html.erb, app/views/tasks/new.html.erb
General tidying up 
Text label changes
Capitalising titles
Photo upload buttons
=> tidying up

app/assets/stylesheets/components/_navbar3.scss
=> hover menu

app/views/layouts/application.html.erb, app/views/shared/_navbar3.html.erb
=> Revert "reparee"

app/models/category.rb, app/views/actions/index.html.erb, app/views/shared/_navbar3.html.erb, app/views/users/show.html.erb
"My Group: add Manage Group - users can now be added to group. No need for seed!"
=> Manage My Group

app/assets/stylesheets/components/_button.scss, app/views/pages/home.html.erb
=> add btn enter home

app/assets/stylesheets/components/_button.scss
=> Branchbranch

app/assets/stylesheets/components/_cards.scss, app/javascript/components/card.js, app/javascript/packs/application.js, app/views/categories/index.html.erb, app/views/option_categories/index.html.erb
fix bug What et JS card category
=> fix bug What et JS card category

Gemfile.lock, app/views/actions/index.html.erb, app/views/assigned_tasks/index.html.erb, app/views/categories/index.html.erb, app/views/option_categories/index.html.erb, app/views/options/index.html.erb
coucou ! derniers petits changements (I hope)
=> petits changements

app/views/categories/index.html.erb, app/views/option_categories/index.html.erb, app/views/options/index.html.erb, package.json, yarn.lock
=> last commit(

app/views/layouts/application.html.erb
=> ajout favicon
